### ISSUE TITLE
allow binary to be stored anywhere in a package

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#1076]
not sure what happened here

i know there are a few packages like tomcat for instance that store their binary in a known folder under sysroot rather than in the main package folder

```
➜  tomcat_9.0.19 cat package.manifest
{
  "Program": "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java",
```

```
➜  ~ ops pkg load tomcat_9.0.19
2021/06/10 10:25:35 open /Users/eyberg/.ops/packages/tomcat_9.0.19/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java: no such file or directory
```

we should definitely allow this for at least packages - i'm assuming this got broke accommodating some usecase for 'run'

i'd make a test for this so we ensure it doesn't regress again in the future

**Comment by francescolavra** [comment]
This got broken as written in the comment at https://github.com/nanovms/ops/pull/1032#discussion_r633074763

**Comment by arknable** [comment]
The PR feels like a workaround I think ... imho, the root issue is the inconsistent format of `Program` field value in manifest file. if the package does not provide root binary, then the path should be like this

```
tomcat_9.0.19/sysroot/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
```

because other packages specify their root binary path using module folder name such as ` node_v14.2.0/node`.
