### ISSUE TITLE
Ops on docker containers 

### ISSUE THREAD

**Issue by podman2020** [nanovms/ops#1089]
Ops commands are very slow in docker containers running on redhat VMs ,any suggestions?

**Comment by eyberg** [comment]
yes, 2 reasons:

1) you should never be running these inside vms to begin with as they run vms themselves - you can use nested virtualization if you need to be inside a vm but that's really something we'd suggest not to do; when pushing to prod (eg: public cloud) they get deployed as vms

2) running inside docker inside of a vm is going to further slow things down since docker will impose it's own networking on top - so you're going to see even more slowdown

are you just trying to run locally? on linux/osx/windows? or are you trying to push to prod? - if running locally you should be able to run this natively on all 3 of those platforms without putting them inside of a vm or a container

**Comment by eyberg** [comment]
yes, 2 reasons:

1) you should never be running these inside vms to begin with as they run vms themselves - you can use nested virtualization if you need to be inside a vm but that's really something we'd suggest not to do; when pushing to prod (eg: public cloud) they get deployed as vms

2) running inside docker inside of a vm is going to further slow things down since docker will impose it's own networking on top - so you're going to see even more slowdown

are you just trying to run locally? on linux/osx/windows? or are you trying to push to prod? - if running locally you should be able to run this natively on all 3 of those platforms without putting them inside of a vm or a container

**Comment by podman2020** [comment]
Thank you for response.
We are just doing POc, the main driver for this to make the ops as  docker container is to easily setup ops.

I think I found the problem. Ops command is trying to reach internet prior to local , is there anyway we can disable reaching internet first ?

**Comment by eyberg** [comment]
can you elaborate a bit? which command you are having problems with?

are you saying the install is trying to reach the internet or you are trying to load a package? or you are wanting to run offline/air-gapped?

the install will need internet access to get the latest kernel/boot but that's a one-time thing and should be fairly fast; whenever you first use a package it will want to download that too - but assuming you have all of that there is no need to be connected to the net

**Comment by podman2020** [comment]
Okay . So I have ops binaries compiled and ready to use .
So when I run any command I.e ops version , or ops pkg list , it waits for 30 seconds and displays the output .

it also displays below warning message:
Version lookup failed, using local.

**Comment by eyberg** [comment]
well both ops version and ops pkg list will definitely ping the internet; the prior to ensure you are up to date with version and the latter to ensure you have the latest manifest but 30 seconds seems incredibly long - it should be basically instant - the manifest for ops pkg list is only 15k, have you just tried running ops outside of the container and outside of the vm? do you see a difference in latency?

the other suggestion is depending on where in the world you are - you could set OPS_PACKAGE_BASE_URL and OPS_PACKAGE_MANIFEST_URL to a closer-to-home mirror (it can even be set to something like file:/// for local mirroring)

but I would start with running the list outside of the container && vm and see if that is faster first

**Comment by podman2020** [comment]
It works perfectly fine when I run on vm that is outside the container , it just takes few seconds. I will try to run other commands .

**Comment by eyberg** [comment]
a drop from 30 seconds to 2 seconds sounds like something is really hosed inside that container - both the version/manifest queries are simple flat-file requests - I think once you have the manifest it doesn't even do a second query - it's just a simple HEAD request so we're talking tens of bytes then

as I mentioned before - ops is really meant to be ran directly on the computer and should work perfectly fine on windows/mac/linux - if you're wanting a better install experience we could certainly look at adding other options for that

2 seconds is still not ideal but is reasonable if you're far away latency wise; we could look at adding some cdn options in the future as right now it's stuffed into a bucket

**Comment by podman2020** [comment]
Thanks
