### ISSUE TITLE
Problem Running R Shiny App

### ISSUE THREAD

**Issue by gfleetwood** [nanovms/ops#1238]
Hi, I'm on Ubuntu 20.04 trying to run the default app example for R Shiny using this code as reference:

https://github.com/nanovms/ops-examples/tree/master/R

In my shiny_ex folder I have a couple of files. app.R, my config.json which is below:

```
{
"files":["hi.r", "app.R", "shiny_1.1.0.tar.gz"],
"Args":["hi.r"]
}
```

hi.r as the entrypoint:

```
install.packages("shiny_1.1.0.tar.gz", repos = NULL, type = "source")
runApp('.', launch.browser = TRUE)
```

And shiny_1.1.0.tar.gz. 

The only library I need is shiny. I initially tried to install it the usual way - without the tarball - with `install.packages("shiny")` but got this:

```
$ ops pkg load R_3.4.4 -c config.json   
 100% |████████████████████████████████████████|  [0s:0s]
booting /home/gordon/.ops/images/R ...
en1: assigned 10.0.2.15
Installing package into '/usr/lib/R/site-library'
(as 'lib' is unspecified)
Error in contrib.url(repos, type) : 
  trying to use CRAN without setting a mirror
Calls: install.packages -> grep -> contrib.url
Execution halted
Warning message:
system call failed: Function not implemented 
```

I switched to copying over my local copy of shiny to op's `/usr/lib/R/site-library` with MapsDirs but it was built on my local R 3.6.3 which is (seems to be?) incompatible with R 3.4.4 (from ops). I looked up when R 3.4.4 was released (March 2018) and then downloaded the previously mentioned tar file for the shiny library version closest to that time:

https://cran.r-project.org/src/contrib/Archive/shiny/

That gave me this:

```
ops pkg load R_3.4.4 -c config.json
 100% |████████████████████████████████████████|  [0s:0s]
booting /home/gordon/.ops/images/R ...
en1: assigned 10.0.2.15
Installing package into '/usr/lib/R/site-library'
(as 'lib' is unspecified)
Warning messages:
1: In system2(cmd0, args, env = env, stdout = output, stderr = output) :
  system call failed: Function not implemented
2: In install.packages("shiny_1.1.0.tar.gz", repos = NULL, type = "source") :
  installation of package 'shiny_1.1.0.tar.gz' had non-zero exit status
Error in runApp(".", launch.browser = TRUE) : 
  could not find function "runApp"
Execution halted
Warning message:
system call failed: Function not implemented
```
In my usual environment I can see the stderr output but if I had to guess it's a dependency issue (https://cran.r-project.org/web/packages/shiny/index.html). I tried to run the recommended ops debugging process to confirm.

```
# in one terminal
ops pkg load R_3.4.4 -c config.json -d

# in another terminal
gdb ~/.ops/0.1.27/kernel.img
(gdb) target remote localhost:1234
(gdb) symbol-file hi.r
`/home/gordon/workspace/unik/shiny_ex/hi.r': can't read symbols: file format not recognized.
```
Is this expected behavior? On a different not, why does ops not use RScript/Rscript to run scripts from the command line?

**Comment by eyberg** [comment]
yeh, there's a handful of things here:

1) the install.packages command should be ran outside of Nanos (in your local dev env) as just installing Shiny on a fresh system installs quite a lot of stuff and during that installation there is a bunch of compilation going on which wouldn't work inside Nanos - so you are correct that you'll want to copy over a local install - using ```.libPaths()``` I ended up copying in local packages to 'usr/lib/R/site-library' but then ran into the same issue you have of not having the right version which brings us to...

2) yeh, you'll need to have a different R package - you can try your hand at crafting your own or wait for one of us to provide another updated one but if you take a look at ~/.ops/packages/R_3.4.4 that gives you a template that you could work with

3) I don't know what app.r you were using but keep in mind that this line ```launch.browser = TRUE) :``` isn't going to work because these are ran inside of vms and are not intended to be ran interactively

4) in answer to your question about RScript - basically that is a wrapper around R which shells out (which we won't ever support in any form) and just passes a few flags so we created an R package that does the same thing - if you pop open 'strace Rsript' you'll see we match it in the package manifest to have the same flags:

```
➜  ~ cat ~/.ops/packages/R_3.4.4/package.manifest
{
   "Program":"/usr/lib/R/bin/exec/R",
   "Args" : ["R", "--slave", "--no-restore", "-f"],
  "Env": {
    "R_HOME": "/usr/lib/R"
  },
   "Version":"3.4.4"
}
```

5) finally the debugging instructions you ran into are for debugging actual binary/elf files - hi.R is a script the R interpreter will load itself whereas R is the actual program being ran

**Comment by gfleetwood** [comment]
I tried creating my own package but it didn't work.

* I copied R_3.4.4 from ~/.ops/packages and renamed it to R_3.6.3,

* I updated the manifest to version 3.6.3

* After looking through the sysroot directory the only thing that seemed R version specific was sysroot/usr/lib/R, so I deleted that folder and replaced it with /usr/lib/R.

* I moved R_3.6.3 to ~/.ops/packages

* I replaced the old shiny package I had installed with the newest one: `remotes::install_version("shiny", lib = "/home/gordon/workspace/unik/shiny_ex/usr/lib")`

* Then I updated my config.json:

`
{
"MapDirs": {
"/home/gordon/workspace/unik/shiny_ex/usr/lib/*": "/usr/local/lib/R/site-library"
},
"files":["hi.r", "app.R"],
"Args":["hi.r"]
}
`
Then I got this when trying to run it:

`
$ ops pkg load R_3.6.3 -c config.json
 100% |████████████████████████████████████████|  [1s:0s]
booting /home/gordon/.ops/images/R ...
en1: assigned 10.0.2.15
Error in readRDS(mapfile) : 
  cannot read workspace version 3 written by R 3.6.3; need R 3.5.0 or newer
Execution halted
Warning message:
system call failed: Function not implemented 
`
