### ISSUE TITLE
Issue(provider): [DO - Digitalocean] - Droplet create event failed, please try again

### ISSUE THREAD

**Issue by rinor** [nanovms/ops#1405]
Are there any new known issues on DO that prevent successful `nanos` deployments?

For some reasons the instances (droplets) created by `nanos` images fail to be created/instantiated properly.
![digitalocean_nanos](https://user-images.githubusercontent.com/1160245/212288364-75729e30-23bc-4a6d-9ecc-55ed7edf6d8b.png)

```
➜  ops image create boringtun-cli -c config.json -t do -z nyc3 -i boringtun   
do image 'boringtun' created...
➜  ops instance create boringtun -t do -c config.json
do instance 'boringtun-1673602491' created...
```
---
- **config.json**
```json
{
  "Program": "boringtun-cli",
  "Args": [
    "--foreground",
    "--disable-drop-privileges",
    "--verbosity",
    "info",
    "wg2"
  ],
  "Env": {
    "WG_CONFIG_FILE": "wireguard.wire"
  },
  "Files": [
    "wireguard.wire"
  ],
  "Dirs": [
    "var"
  ],
  "BaseVolumeSz": "10G",
  "RunConfig": {
    "Klibs": [
      "tun"
    ],
    "UDPPorts": [
      "51820"
    ],
    "CanIPForward": true
  },
  "ManifestPassthrough": {
    "tun": {
      "wg": {
        "ipaddress": "10.0.0.1",
        "netmask": "255.255.255.0",
        "up": "true"
      }
    }
  },
  "CloudConfig": {
    "Platform": "do",
    "Zone": "nyc3",
    "BucketName": "ops",
    "Flavor": "s-1vcpu-1gb"
  }
}
```
---
**Note**:
- Tried also to create the droplets manually from the ops uploaded image and still the same result.
- Tried both formats `.qcow2` and `.raw`
- Tested with `qemu` versions `5.2` and `7.2`
- Tested with Nanos version: `0.1.43`, `nightly`, `master branch`

**Comment by francescolavra** [comment]
There are no known issues with running Nanos on DO, in fact I just tried creating a Nanos image and then a droplet, and everything seems to work fine:
![Screenshot from 2023-01-13 17-58-44](https://user-images.githubusercontent.com/10710577/212377670-bb1dc540-80ce-4626-b077-414b761c1c08.png)
My droplet is running an example program instead of boringtun, but I don't think this makes a difference, it seems to me you encountered a problem with DigitalOcean. I'm using sfo3 as zone instead of nyc3, but this shouldn't make a difference either.
I also tried creating the droplet manually from the uploaded image (also tried with different instance flavors), and it worked flawlessly. Tested with Nanos 0.1.43 and nightly.
Perhaps there was a transient issue in DigitalOcean when you were using it? Your error message says "please try again in a few minutes".

**Comment by rinor** [comment]
Ok, thanks. Will try other zones and apps jic. Maybe I'm missing smth in the config file.

> Perhaps there was a transient issue in DigitalOcean when you were using it? Your error message says "please try again in a few minutes".

It's 3 days in a row now.

Thank you.

**Comment by eyberg** [comment]
it could easily be booting and dying very fast - if you haven't tried a simple hello world there first I'd prob do that to see if you could even do that before tackling the wireguard app

**Comment by rinor** [comment]
Indeed started fresh again today.
- tested some `simpler` apps and they work perfectly.
- tested `wireguard-go` and it works as expected

Will get back to checking `boringtun-cli`, just to understand what the issue is and if it's related to `nanos`.

Thank you.

**Comment by rinor** [comment]
It ends up that on DO, the tun interface comes up as `wg3` instead of `wg2` and while `wireguard-go` can autoswitch to that wg3 even when instructed to expect wg2, `boringtun-cli` needs the exact name.

So indeed the instance was fast failing hence DO deleted it.
