### ISSUE TITLE
How to package a program on the outer layer of a public package？

### ISSUE THREAD

**Issue by leeyiding** [nanovms/ops#1624]
Hello, I need to wrap another program on the outside of `pkg eyberg/python:3.10.6`.
For example, the program is called `wrapper` and runs in a format like `wrapper python3 test.py`, how can I achieve my goal based on `eyberg/python:3.10.6`?

**Comment by eyberg** [comment]
can you give an example? if it's python then you just execute it using '-a test.py'

if it's not python and it's a diff. program than that's not something we support

**Comment by leeyiding** [comment]
like this: https://github.com/Juice-Labs/Juice-Labs/wiki/Run-Juice
I need the Python environment, but `juicify` as the first parameter and `python3` as the second parameter

**Comment by eyberg** [comment]
no, you wouldn't be able to use this the way it works today as nanos only supports running one program, however, it looks like they use this libjuicejuda to provide the functionality; so i imagine getting this functionality, espc. since it's a client/server model should be straight-forward enough if that lib was available; i was looking around for that and didn't find it immediately  though - it looks like they've halted their community version too
