### ISSUE TITLE
Qemu `--enable-kvm` can fail in nested environments

### ISSUE THREAD

**Issue by ExternalReality** [nanovms/ops#186]
If using `ops` in a virtual environment the `--bridge` option may fail if nested virtualization is not enabled in the environment since the `--bridged` flag implies a qemu `--enable-kvm` option. Should there be a check for `kvm` before trying to enable it?

**Comment by eyberg** [comment]
hrm there are a few things here:

* the title suggests that there is a problem w/kvm in nested environments - but I don't think that's the case? it's the problem that it won't work w/out hardware acceleration which is either on metal or in a nested virtualization env.

* bridges don't require virtualization but they do require root perms - there are a few ways of approaching this - you can

1) require the user to sudo
2) give it suid (most sec ppl frown on this even though it's no more harmful than anything else)
3) pass it capabilities (this would prob. be a good option for a default install from curl on the website but complicates the install for building from source), also - I am unaware of the equivalent on osx - however that's ok cause the prevalence of no-wired environments && no factory default acceleration (w/out installing intel hax)

lastly - I would state that bridging probably makes no sense if you can't use hardware acceleration cause that's going to slow things down way more than anything

anyways... 

to check on linux:
egrep '(vmx|svm)' /proc/cpuinfo

to check on osx:
kextstat | grep -c hax

so sorry it's not a yes/no question but one quick/easy fix would be to put some warnings (rather than just flailing about w/a panic message) stating that it can't find/enable hardware acceleration

**Comment by eyberg** [comment]
i'm closing this for now - a true nested env should be working fine (google nested virt for instance), we also have chks for kvm now
