### ISSUE TITLE
readme should link to 'getting started' hello world examples

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#198]
just include a link to each language's getting started in the gitbook https://nanovms.gitbook.io/ops/

**Comment by ExternalReality** [comment]
https://github.com/nanovms/ops/pull/205

**Comment by ExternalReality** [comment]
This issue does highlight the fact that `Ruby` is left out of the loop here. I wouldn't mind adding a `Rails` or `Sinatra` basic usage example. `Rails` programmers are smart and progressive and love easy-to-use tools like `ops`. It would be ashamed to leave them out of the fun. I wonder if @Truemedia was attempting to load a `Rails` application in https://github.com/nanovms/ops/issues/189.

As a former Lisp-oholic I think Lisp programmers are really deserving of a basic usage example too. Oh, the pain of being the lonely Lisp programmer that is always left out of the fun. Well, given that the size of a hello world program "standalone executable" for many Common Lisp platforms is quite lofty we can't have the size overhead of the vm/container being lofty as well. Perhaps a `Steel Bank/CMUCL` basic usage example would be cool too if it works (you wouldn't need a new package since you can easily build an ELF image with those platforms).

**Comment by eyberg** [comment]
we'll have better ruby here shortly, to wet your appetite there's chicken scheme -> https://github.com/nanovms/ops-examples/tree/master/scheme/01-hello-world - sbcl in the list - closing this issue for now though since it's g2g
