### ISSUE TITLE
Interacting with attached disks

### ISSUE THREAD

**Issue by daxpedda** [nanovms/ops#508]
Is it possible or planned to access and write to other disks like for example attached disks on google cloud?

The use case I'm thinking of right now is how to update an application that needs persistent file storage other then modifying the already existing image.
It seems quite important to me actually, are there other ways people solve this right now?

EDIT: I actually searched for quite a while before I wrote this issue, but right after submission I saw #489, I'm assuming thats what I'm looking for?

**Comment by eyberg** [comment]
you're correct right now we just support allowing persistent changes to the same image, there most definitely is plans for attaching extra disks w/the precise use-case you mentioned - we just haven't done the work yet, it's not in the immediate priority list but it is something we wish to tend to sooner rather than later now that we are supporting quite a handful of various databases

**Comment by eyberg** [comment]
we have basic volume support everywhere now (I think azure is the only place ops is missing support) so closing this for now - lmk if you try this out - https://nanovms.gitbook.io/ops/google_cloud#volume-operations -  and have suggestions/bugs/etc.
