### ISSUE TITLE
volume.json file doesn't save data in valid JSON format

### ISSUE THREAD

**Issue by ahmedaabouzied** [nanovms/ops#647]
## Description
The insert method on the JSONStore appends to the file invalidating the JSON format. This makes it necessary to loop through all the lines in the file just to look up one entry.
https://github.com/nanovms/ops/blob/873c4d2504f571f16ead6731f6a671c7b59b98af/lepton/store.go#L18-L30

## Example
This is used to store volumes in the `volumes.json` file. Making it necessary to loop through all the volume entries in the file and decode each one separately just to look up one volume by its UUID.
https://github.com/nanovms/ops/blob/873c4d2504f571f16ead6731f6a671c7b59b98af/lepton/store.go#L33-L54

I don't know if this was an intended behaviour for some reason or not, @eyberg , @ronaudinho

**Comment by ronaudinho** [comment]
the `volume.json` contains newline-delimited JSON, so i believe they are valid JSON still, but doing it this way makes it impossible to unmarshal them into structs for other operations, which makes `Get` inefficient.

after looking at implementations in `ops image` and `ops instance`, I am thinking of actually scraping this and simply scan the default dir to look for existing ops volumes just like those two.

**Comment by eyberg** [comment]
no, that's not valid json..

**Comment by ronaudinho** [comment]
my bad i should've said each line is valid JSON and the whole file is [ndjson](http://ndjson.org/).
[this article](https://medium.com/@kandros/newline-delimited-json-is-awesome-8f6259ed4b4b) more or less summarizes my initial design reasons.
example usage i can remember is [bigquery requires ndjson for loading data](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-json)

> Making it necessary to loop through all the volume entries in the file and decode each one separately just to look up one volume by its UUID.

actually, once a matching volume is found, the file can be closed e.g here the loop break when match is found or if none found, break on `EOF`
https://github.com/nanovms/ops/blob/873c4d2504f571f16ead6731f6a671c7b59b98af/lepton/store.go#L33-L54
as opposed to using valid JSON array, where we have to unmarshal the whole file to find a matching entry e.g
```
var vols []NanosVolume
b, _ := ioutil.ReadFile(s.path) // read whole file
json.Unmarshal(b, &vols) // unmarshal whole file
for _, vol := range vols {
  // loop to find matching id
}

```

another thing is, for insertion, it's a lot faster since it simply encodes 1 json and append to file, as opposed to modifying a whole JSON array (e.g unmarshal current JSON list into array of struct, append to that array, marshal and write to file)

anyway, the upcoming volume label integration i'm working on will remove this to make the `list` command implementation standardized with `ops image` and `ops instance`

**Comment by eyberg** [comment]
this isn't using json anymore but i'm not sure if the symlink replacement is necessary either; anyways that'd be a diff issue, closing this one

**Comment by ahmedaabouzied** [comment]
I'll go through the new implementation
