### ISSUE TITLE
once tmp image is created it should be removed in favor of the disk image (volume) on gcloud

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#681]
on other providers like aws we don't keep any images (instance images too) in the bucket as an ami gets created after

**Comment by arknable** [comment]
@eyberg could you please elaborate how to reproduce this ? and what command associated with this issue ?

**Comment by fabioDMFerreira** [comment]
The command associated with this issue is the `ops image create`. The way to reproduce this is to create an image in a cloud provider and make sure the artefacts created to deploy the image are deleted.

Before uploading the image to a cloud provider we need to build it locally. So, we want to make sure that the image built locally is deleted after uploading it to the cloud provider.

**Comment by eyberg** [comment]
to clarify (i believe) we upload raw disk format to gcloud and that's what we use locally so i think this is referring to the artifacts in the bucket - but i don't know if that works the same way like aws

**Comment by fabioDMFerreira** [comment]
I confirmed it works. First, we upload the raw file to the bucket, then we create the image by importing it from the bucket.

**Comment by fabioDMFerreira** [comment]
There's no need on keeping the artifact in the bucket. I misread it and thought it was related to the artifacts in the local machine.

**Comment by eyberg** [comment]
if this is converted over I think 'images list' and all those operations will need to be refactored as well so should verify we can work with those as well

**Comment by arknable** [comment]
I think other subcommands seems fine
