### ISSUE TITLE
re-attaching a new volume to gcloud seems to require a full start/stop not just reset

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#685]
when attaching a volume to an instance you can do a soft reset to get the new volume contents recognized (covered in https://github.com/nanovms/ops/issues/684) but when re-attaching it seems to be the case that a full stop/start is required

@francescolavra unless there is something nanos side going on - i'm assuming this is just how their underlying kvm implementation works? it's ok if so - not a huge deal

**Comment by francescolavra** [comment]
@eyberg what does re-attaching a disk mean exactly? Is it just the combination of detaching a volume and then attaching another volume with the same label?

**Comment by eyberg** [comment]
yes, when I was playing around it seemed that for the first attach i just had to do a soft reset but for any other detaching, re-attaching (new volume with new contents but same label) I had to do a full start/stop - it is pretty fast so it's ok if we are stuck with that for now

**Comment by francescolavra** [comment]
I'm unable to reproduce the issue. Here is what I did:
- created a GCP image with `ops image create -c config-gcp.json --mounts mntt:/b -t gcp -a getdents` (getdents is a binary from the Nanos runtime tests, modified to list the contents of the directory /b and to not terminate after it's done, so that the VM does not restart continuously)
- started an instance with `ops instance create -t gcp -c config-gcp.json -i getdents-image`
- created a volume with `ops volume create mntt -c config-gcp.json -t gcp -d dir1`
- attached the volume with `ops volume attach getdents-image-1602773324 mntt b -c config-gcp.json -t gcp`
- restarted the instance form the GCP portal, by clicking on the reset button
- verified from the instance logs that it lists the contents of dir1
- detached the volume with `ops volume detach getdents-image-1602773324 mntt -c config-gcp.json -t gcp`
- deleted the volume with `ops volume delete mntt -c config-gcp.json -t gcp`
- created another volume with `ops volume create mntt -c config-gcp.json -t gcp -d dir2`
- attached the new volume with `ops volume attach getdents-image-1602773324 mntt b -c config-gcp.json -t gcp`
- restarted the instance form the GCP portal, by clicking on the reset button
- verified from the instance logs that it lists the contents of dir2
