### ISSUE TITLE
azure doesn't allow image to be deleted when being 'provisioned'

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#766]
what's going on here is that this was spun up about a week ago but since we have the outstanding issue where the deployment never really finishes (even though the instance is stood up) you get this false error

```compute.ImagesClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="Operation 'Image Delete' is not allowed since the Virtual Machines 'udpserver-image,udpserver-test' are being provisioned using the Image 'udpserver-image'."```

I think we should probably wait to see if we can fix this via https://github.com/nanovms/nanos/issues/1319 - but if not there is probably a way to cancel this or at least make it go away after the instance has been brought up

**Comment by francescolavra** [comment]
I couldn't reproduce the issue:
```
francesco@ubuntu:~/.ops/instances/go$ /usr/src/ops/ops instance delete -t azure gtest-image1605889062
Instance deletion completed
francesco@ubuntu:~/.ops/instances/go$ /usr/src/ops/ops image delete -t azure gtest-image
{Future:{pt:0xc00052e000}}Started deleting image from container
Image gtest-image deleted successfully
```
I created the instance using a modified Ops, with `ProvisionVMAgent: to.BoolPtr(false)` (see https://github.com/nanovms/nanos/issues/1319), not sure if it has something to do with this. Anyway, the instance creation via Ops had previously timed out due to the known provisioning problems, and the instance state was still showing up as "Creating" in the Azure portal; yet, I could delete both the instance and the image without errors.

**Comment by eyberg** [comment]
this https://github.com/nanovms/ops/commit/13e88e25d01c4022b077ecbff908d3e6ca0d240f might've fixed some of these issues as before we weren't removing all of these resources but now we are
